In [1]:
# 導入函式庫
import os
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.datasets import mnist
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.utils import np_utils  # 用來後續將 label 標籤轉為 one-hot-encoding  
from matplotlib import pyplot as plt

In [2]:
# target data
pre_lea_2021_data = pd.read_csv(os.getcwd() + '\\pre_lea_2021_data.csv')
pre_lea_2021_data

,result,HF,AF,H1N_age,H1N_height_cm,H1N_weight_kg,H1N_overall,H1N_potential,H1N_value_eur,H1N_wage_eur,...,A11N_gk_kicking,A11N_gk_reflexes,A11N_gk_speed,A11N_gk_positioning,A11N_goalkeeping_diving,A11N_goalkeeping_handling,A11N_goalkeeping_kicking,A11N_goalkeeping_positioning,A11N_goalkeeping_reflexes,A11P_positionScore
0,away,4-2-3-1,3-4-3,25,181,70,70,74,2200000,47000,...,80,86,56,84,85,83,80,84,86,84
1,home,4-4-2,4-4-2,28,181,70,77,77,11000000,59000,...,64,81,57,75,77,75,64,75,81,75
2,home,4-3-3,4-1-4-1,28,181,70,87,87,81500000,190000,...,70,73,28,67,70,67,70,67,73,67
3,away,4-2-3-1,4-4-2,30,181,70,78,78,14000000,46000,...,64,76,55,71,75,70,64,71,76,71
4,away,3-4-3,4-1-4-1,25,181,70,72,76,3300000,53000,...,83,89,54,79,82,77,83,79,89,79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,home,4-2-3-1,4-4-2,33,181,70,84,84,27000000,175000,...,64,81,57,75,77,75,64,75,81,75
209,away,4-4-2,4-3-3,28,181,70,73,73,3100000,44000,...,93,88,63,86,86,82,93,86,88,86
210,away,3-4-3,4-2-3-1,25,181,70,77,80,14000000,90000,...,83,89,54,79,82,77,83,79,89,79
211,away,4-1-4-1,4-2-3-1,26,181,70,71,72,2200000,56000,...,76,78,36,78,78,77,76,78,78,78
212,away,4-2-3-1,4-2-3-1,24,181,70,76,81,11500000,49000,...,70,82,48,81,80,82,70,81,82,81

In [3]:
X = pre_lea_2021_data.drop(['result'], axis = 1).copy()

X_encoded = pd.get_dummies(X, columns=['HF', 'AF'])
X_encoded

,H1N_age,H1N_height_cm,H1N_weight_kg,H1N_overall,H1N_potential,H1N_value_eur,H1N_wage_eur,H1N_international_reputation,H1N_weak_foot,H1N_skill_moves,...,AF_3-5-2,AF_4-1-4-1,AF_4-2-2-2,AF_4-2-3-1,AF_4-3-2-1,AF_4-3-3,AF_4-4-1-1,AF_4-4-2,AF_4-4-2◆,AF_4-5-1
0,25,181,70,70,74,2200000,47000,1,3,3,...,0,0,0,0,0,0,0,0,0,0
1,28,181,70,77,77,11000000,59000,2,3,4,...,0,0,0,0,0,0,0,1,0,0
2,28,181,70,87,87,81500000,190000,3,4,5,...,0,1,0,0,0,0,0,0,0,0
3,30,181,70,78,78,14000000,46000,2,3,4,...,0,0,0,0,0,0,0,1,0,0
4,25,181,70,72,76,3300000,53000,1,3,3,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,33,181,70,84,84,27000000,175000,4,4,3,...,0,0,0,0,0,0,0,1,0,0
209,28,181,70,73,73,3100000,44000,1,4,3,...,0,0,0,0,0,1,0,0,0,0
210,25,181,70,77,80,14000000,90000,1,4,3,...,0,0,0,1,0,0,0,0,0,0
211,26,181,70,71,72,2200000,56000,1,3,3,...,0,0,0,1,0,0,0,0,0,0
212,24,181,70,76,81,11500000,49000,1,4,3,...,0,0,0,1,0,0,0,0,0,0

In [10]:
X_encoded.dtypes

H1N_age          int64
H1N_height_cm    int64
H1N_weight_kg    int64
H1N_overall      int64
H1N_potential    int64
                 ...
AF_4-3-3         uint8
AF_4-4-1-1       uint8
AF_4-4-2         uint8
AF_4-4-2◆        uint8
AF_4-5-1         uint8
Length: 950, dtype: object

In [4]:
y = pre_lea_2021_data['result'].copy()

# def one_hot_y_label(y):
#     result = np.zeros((len(y), 3), dtype=int)
#     for ind, rs in y.items():
#         if rs == 'home':
#             result[ind][0] = 1
#         elif rs == 'away':
#             result[ind][2] = 1
#         else:
#             result[ind][1] = 1
            
#     return result.astype('float32')

def one_hot_y_label(y):
    result = np.zeros(len(y), dtype=int)
    for ind, rs in y.items():
        if rs == 'home':
            result[ind] = 1
#         elif rs == 'away':
#             result[ind] = 1
#         else:
#             result[ind] = 1
            
    return result.astype('float32')


# 將 training 的 label 進行 one-hot encoding，例如數字 7 經過 One-hot encoding 轉換後是 0000001000，即第7個值為 1
y_encode = one_hot_y_label(y)
y_encode

array([0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0.,
       0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
       1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 1., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [5]:
# 建立簡單的線性執行的模型
# model = Sequential()
# # Add Input layer, 隱藏層(hidden layer) 有 256個輸出變數
# # model.add(Dense(units=256, input_dim=28*28, kernel_initializer='normal', activation='relu')) 
# model.add(Dense(units=300, input_dim=950, kernel_initializer='normal', activation='relu')) 
# # Add output layer
# model.add(Dense(units=3, kernel_initializer='normal', activation='softmax'))

model = Sequential()
model.add(Dense(600, input_dim=950, activation='relu'))
model.add(Dense(300, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [6]:
# 編譯: 選擇損失函數、優化方法及成效衡量方式
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [7]:
X_encoded.values

array([[ 25, 181,  70, ...,   0,   0,   0],
       [ 28, 181,  70, ...,   1,   0,   0],
       [ 28, 181,  70, ...,   0,   0,   0],
       ...,
       [ 25, 181,  70, ...,   0,   0,   0],
       [ 26, 181,  70, ...,   0,   0,   0],
       [ 24, 181,  70, ...,   0,   0,   0]], dtype=int64)

In [8]:
# 進行訓練, 訓練過程會存在 train_history 變數中
# train_history = model.fit(x=x_Train_norm, y=y_TrainOneHot, validation_split=0.2, epochs=10, batch_size=800, verbose=2)  
train_history = model.fit(x=X_encoded.values, y=y, validation_split=0.2, epochs=10, batch_size=800, verbose=2)

Epoch 1/10

UnimplementedError:  Cast string to float is not supported
	 [[node categorical_crossentropy/Cast (defined at <ipython-input-8-91deed207d22>:3) ]] [Op:__inference_train_function_669]

Function call stack:
train_function

In [ ]:
X_encoded.values